title: Beware of programmers carrying screwdrivers
email: esm@logic.net
description: >
  Words about devops and engineering that occasionally form coherent thoughts.
baseurl: ""
url: "http://code.logic.net"
twitter_username: esm
github_username:  logic

markdown: kramdown
highlighter: pygments
paginate: 10
permalink: /:year/:month/:title/
